#!/bin/bash

cd $(dirname $0)

while getopts "b" arg; do
  case $arg in
    b)
      bash bookdown/build
      ;;
  esac
done
shift $(($OPTIND-1))

git add -A
git commit --amend -m ':tada:' -q
git push -f -q --progress
git reflog expire --expire-unreachable=now --all
